---
- name: Install software
  hosts: all
  become: true
  vars:
    packages:
      - nmap
      - httpd
      - php

  tasks:

  - name: Install Software
    yum:
      name: "{{ packages }}"
      state: present
